### ISSUE TITLE
Go 1.24 not supported on latest actions marketplace version

### ISSUE THREAD

**Issue by djames-bloom** [qbaware/nilaway-action#26]
When running on a codebase with `go.mod` setting the toolchain version to `v1.24` (released 2025-02-11) this action will fail.

Replicated on `self-hosted` and `ubuntu-latest` workers.

Workflow file:
```yaml
jobs:
  nilaway:
    name: 'nilaway'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v5'
        with:
          go-version: '1.24'
      - name: 'Run nilaway'
        uses: 'qbaware/nilaway-action@v0.0.12'
        with:
          package-to-scan: './...'
```

Pre-setup step works as expected

```
Run actions/setup-go@v5
Setup go version spec 1.24
...
go version go1.24.1 linux/amd64

go env:
  GOVERSION='go1.24.1'
```

Running of this action fails due to an upper bound of `Go 1.23.3`

Action output:
```
nilaway: err: exit status 1: stderr: go: go.mod requires go >= 1.24 (running go 1.23.3; GOTOOLCHAIN=local)
```
